### PR TITLE
Fix Debian packages file

### PR DESCRIPTION
**Pull request by rpasche**
Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1226329
If the version is preceeded with operators, add an extra space between operator and version to be parseable.

I have to tell, that I was not able to fully test this (in spacewalk), but made a small test script. It should work, to change a version line (e.g. "<<1.3.4-5" to "<< 1.3.4-5")

### CODE REVIEW

**Comment by tlestach** [comment]
Note for whoever will review this PR: As stated - this a workaround, not a proper fix. See the Bug 1226329 for more information.

**Comment by rpasche** [comment]
It's true, that this is really only a workaround, but it would help a lot to get around the error I have with Debian 8. Now, I have to re-create the Packages.gz after the taskomatic daemon has created the original Packages file. OK...not really a big deal, but annoying. Also I cannot imagine, how long it will take to fix the root cause of this problem within spacewalk.

**Comment by Thubo** [comment]
Any news on this?

**Comment by rpasche** [comment]
Not as far as I know...

**Comment by ggainey** [comment]
rpasche, Thubo - Could you look at PR#399, and see if it is a 'correct' fix for this problem?

**Comment by rpasche** [comment]
Hi @ggainey ,

just commented the pull request...don't know, when I have time to test it.

**Comment by ggainey** [comment]
@rpasche @Thubo - I'm going to close this PR in favor of the work @tlestach is doing in #399 - would rather have this fixed correctly than hack around the issue, and looks like we may be close to that.

**Pull request closed without merging**
