### PR TITLE
"Pune Encoding" -> Punycode terminology corrections

### PR DESCRIPTION
**Pull request by PaulWay**
The code refers to "Pune encoding" throughout.  This is a misreading of the "Punycode" system of encoding non-ASCII characters in URLs:

https://en.wikipedia.org/wiki/Punycode
http://tools.ietf.org/html/rfc3492

This pull request should contain two commits:

1) Updating the documentation and internal comments to refer to "Punycode (RFC3492)".
2) Updating the function names:

convert_url_from_pune -> convert_url_from_puny
convert_url_to_pune   -> convert_url_to_puny
idn_ascii_to_pune     -> idn_ascii_to_puny
idn_pune_to_unicode   -> idn_puny_to_unicode

Hope this helps,

Paul

### CODE REVIEW

**Comment by xkollar** [comment]
``` .bash
git grep 'convert_url_from_pune\|convert_url_to_pune\|idn_ascii_to_pune\|idn_pune_to_unicode' \
| grep -v '\.spec:'
```

Is it possible that you have forgotten some substitutions? (maybe forgotten /g in sed? `;-)`)

**Comment by xkollar** [comment]
also is possible, please rebase on current master (but I can do that...)

**Comment by PaulWay** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 30/01/15 20:39, Matej Kollar wrote:
> also is possible, please rebase on current master (but I can do that...)

Hi Matej,

I'll do a rebase and a double-check of my sed -i :-)

Thanks,

Paul
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlTODokACgkQu7W0U8VsXYKibgCfVIygc9tRqigR/tKhFMPvri6M
0/EAoIuBU0A/NK/E6pjQCowDmv4N35zd
=3iM5
-----END PGP SIGNATURE-----

**Comment by PaulWay** [comment]
Hi Matej,

I've fixed the remaining mentions of pune in function names, and did what I think is a merge (merged master into my branch, fixed the conflicts, committed the changes, pushed the new commit).

Let me know if that's working for you or I need to do more work to get it into shape :-)

Thanks in advance,

Paul

**Comment by xkollar** [comment]
Hi Paul.

Rebase is something different from merge (`git merge` vs `git rebase`). Never mind though, I have rebased it for you ;-). Plus added little polish, I hope you don't mind (you should chek it in case I messed semehing up). I would have left it for you as an exercise but I am about to change some code near your changes and that might complicate your life a little...

Welcome into prominent club of Spacewalk contributors :+1:.

Rebased on master as:

* 55f848092fc9ba3286553f3cd9d392a74162a6a8
* 6255eb344354a24eeb89c277104516bc3b8044ab

**Comment by PaulWay** [comment]
Hi Matej,

I'm not sure I see the difference in the diffs, but whatever works for you is fine with me :-)  The commits you've made look good.

Have fun,

Paul

**Pull request closed without merging**
