### PR TITLE
Postgresql 9.6 support

### PR DESCRIPTION
**Pull request by dAverk**
Changed "at.label method" to "at.label as method" because 1'st variant causes error on PostgreSQL 9.6

### CODE REVIEW

**Comment by matonb** [comment]
Any idea when this fix will be released ?

**Comment by jdobes** [comment]
Rebased into master. Thanks.

**Comment by jdobes** [comment]
@matonb Plan is to release this in next release of Spacewalk (2.7) in couple of months.

**Comment by matonb** [comment]
@jdobes That's great thanks

**Pull request closed without merging**
