### PR TITLE
1533052 - Add FQDN detection to setup and config utilities.

### PR DESCRIPTION
**Pull request by lrochfor-oracle**
Specifically, spacewalk-setup, spacewalk-hostname-rename, and
spacewalk-setup-jabberd.

FQDN detection is needed for SSL cert generation. If shortname is used
SSL validation fails in numerous components.

See BZ 1533052 for details.

### CODE REVIEW

**Comment by jiridostal** [comment]
The patch looks reasonable. Could you please resolve conflicts so that we can rebase it? Thank you

**Comment by jiridostal** [comment]
merged as f8a7cc0181e2fc3b0e49bb4cc79453289458a21d, d5caec0bae9421ea792dda515732f02de6ac8283

**Comment by lrochfor-oracle** [comment]
Can you elaborate on what you're seeing?
Is your hostname file set to FQDN?
Does your /etc/hosts have IP FQDN shortname entry?
Does your DNS forward and reverse lookup between IP and FQDN?

**Comment by jiridostal** [comment]
Hello, I've just re-tested your patch and didn't run at issue I described above (so I cannot answer your questions...) . However, change of hostname is quite critical thing and I want to be sure that it doesn't break anything, so I'll run some more automated tests.

**Comment by lrochfor-oracle** [comment]
Jiri Dostal writes:

> Hello, I've just re-tested your patch and didn't run at issue I
> described above (so I cannot answer your questions...) . However,
> change of hostname is quite critical thing and I want to be sure that
> it doesn't break anything, so I'll run some more automated tests.

Thanks Jiri,

We didn't encounter any issues here with personal testing, and testing
from our QA team, but of course DNS configs vary quite a lot.

I noticed there are some other areas in the codebase where FQDN
detection isn't done, but they're not related to initial config/setup,
so can probably come in a later PR.

**Comment by jiridostal** [comment]
Okay, I fixed one minor thing in the code and other than that didn't bump at any issue. Merging as 1bcde51c72fd569ba8e36a7f6bdf78e1967c6499 and 6a8bcfde37692bade3cf3882e7934cda47aa38a3

**Pull request closed without merging**
