### PR TITLE
Removal of entitlement counting code

### PR DESCRIPTION
**Pull request by moio**
This PR drops several entitlement-related features from Spacewalk codebase, as discussed on the spacewalk-devel mailing list.

Mainly:
* ebcfabfeba6e461c688c59740c5b642cb68f48f0..1a2261399f4aa006ae25e6646a730d64c45b0e6e: removal of channel entitlements and channel entitlement counting
* 16ac9971570a3163a3cd34f385a2fa778111aa8d..f07a051bded3dbc25c05ff4c4a36b7575bb73de8: removal of monitoring leftovers
* 9982bb96d2a383cafe3ae031a62898955329c7ac..2b4778e48383d82332e28005ea3028636e6d7205: dropping of the "provisioning" system entitlement ("enterprise/management" entitlement gives access to what previously required "provisioning", "provisioning" entitled systems now become "management" entitled)
* df924769e931bc7d4a7ed1d805242d1ccb3df8c8..f25e03d1c2d2a3ca18e2a78a82247c90457828af: dropping of the unused "update" system entitlement (checks and systems again moved to "enterprise/management")
* 826d78e553d6355832f5bbc74034ee2593608ce5..339fc7d54d8d267088041d2fa1fcd439a0406b43: dropping of the unused "nonlinux" system entitlement (systems moved to unentitled);
* 18a70c80de3a525ed3ff617a63bb7cb6d2ac0876..d529f2a7b6bdc516672ed90ac0cef2f3376f36fd: dropping of the unused "virtualization host platform" system entitlement (systems and checks moved to "virtualization host");
* d59582c8c046be1639d12aa2502fe486c26452f4..7f7482209d94ff7243397df7542fb1f9812adf91: removal of system entitlement checks and certificate handling and tooling;
* 205f2e0a8b07dcc7930469c3e14ffe56afdd88d5..d8ed8cbde06f97772ef828c82464f95b606f02ab: removal of Org entitlements.

Note what we did not remove:
 * system entitlements as a concept is still there, we still need a way do differentiate functionality between normal hosts ("management/enterprise") and VM hosts ("virtualization host");
   * at some point we might want to rename "entitlements" into "roles", "feature sets" or some other more meaningful name. The renaming was not done yet because of time constraints, we might provide it later;
 * system entitlement counting is still there, meaning that system groups still retain the ability to count their members. This could be further refactored via `VIEW`s or simple `SELECT COUNT(*) FROM rhnServerGroupMembers ...` queries, again this was not accomplished yet because of time constraints but could come later;
 * unentitled systems are still there, as among other things they are the basis for new kinds of systems we plan to add (notably: Salt minions). We have code ready to fix some bugs in that part, we will open a PR as soon as this one is accepted in Spacewalk.

**Developer benefits**: some 30k LOC removed which were not really adding value to the open source product.

**User benefits**: no more handling of the Spacewalk certificate and its expiration. All Orgs always have unlimited entitlements, so no juggling between them is needed anymore.

**Methodology notes**:
 - code has been continuously pushed here and Travis CI errors have all been dealt with;
 - we submitted all packages to Koji in the devel "branch" as agreed[1], packaging errors have all been dealt with;
 - code has been rebased on top of current master today;
 - nightly packages were published and no bug reports emerged so far as far as I know;
 - developers in the SUSE Manager team have all those commits already, so we developing on top of this. Obvious errors have been discovered already and we will push other bugfixes as soon as they are ready;
 - all jUnit and Python unit tests are passing in the SUSE Manager version and are automatically checked at least daily;
 - our cucumber testsuite also passes in the SUSE Manager version and is automatically checked at least daily;
 - our schema upgrade testsuite passes in the SUSE Manager version;
 - all of this code was peer reviewed either by two or three of us.

While I am pretty sure some bugs are still hiding in between this ~500 commit PR, I feel also quite confident that the average quality is pretty good and look forward for your review.

[1] *Nightly packages for this particular branch are available. You can test them by following the [guide for nightly Spacewalk](https://fedorahosted.org/spacewalk/wiki/HowToInstall) and replacing nightly repo URLs with the following ones*:

​http://yum.spacewalkproject.org/devel/ (server side)
http://yum.spacewalkproject.org/devel-client/ (client side)

### CODE REVIEW

**Comment by lhellebr** [comment]
Breaks satellite-sync from dump:

1) Have an installed Spacewalk and dump directory:
```
# ls dumps
arches  blacklists  channel_families  channels
```

2) Run sync from a dump:
```
# satellite-sync -m dumps// -c rhel-x86_64-server-5
```
[traceback.txt](https://github.com/spacewalkproject/spacewalk/files/32753/traceback.txt)

You can start by viewing this completely untested and unfinished "hotfix" after which the traceback disappears:
```
# diff /usr/lib/python2.7/site-packages/spacewalk/satellite_tools/sync_handlers_OLD.py /usr/lib/python2.7/site-packages/spacewalk/satellite_tools/sync_handlers.py
473c473
<         self.setServerGroupServerArchContainer()
---
>         # self.setServerGroupServerArchContainer()
```

**Comment by mcalmer** [comment]
@lhellebr : Please check if you run the latest code. Especially the last commit added to this branch.

https://github.com/spacewalkproject/spacewalk/commit/c8a8e0d5385a9bca0d372ade770f00ed516c08f6

The traceback show:

File "/usr/lib/python2.7/site-packages/spacewalk/server/importlib/archImport.py", line 152, in _postprocess
    BaseArchCompatImport._postprocess(self)

Line 152 indicate, that you do not have this patch, otherwise it would be line 155.

Please check this an try with the latest code. Thanks.

**Comment by jdobes** [comment]
Merged. Conflicts list when rebasing to master:
- 1 sha1 change (use value from PR commit to avoid conflicts in following commits) caused by bumped copyright year, fix value after rebase
- Remove monitoring entitlement from spacecmd activation key help string - 1 additional space, using version from master, remove commit with "git rebase --skip" because changes from commit were already done
- need to remove manually 4 files with bumped copyright year
- spacecmd: remove references to provisioning entitlements - conflicting same 1 space as above, using version from PR
- need to remove manually 2 files with bumped copyright year
- Remove virtualization_host_platform - new strings at the and of file remove only virtualization platform one
- debian client tools: po files updated - ca and pt lang files don't match, use versions from PR
- rhel client tools: po files updated - ca lang file doesn't match, use version from PR
- java: restricted whitelist dead code removal - delete manually 1 method with extra @Override added
- i18n: unused strings removed - manually delete restricted period translations (grep -lr '<<<<<<<' java/ | xargs git checkout --theirs), due to redundant comma in texts from master

- updated commits to use new upgrade scripts path
- few commits removing monitoring entitlements dissappeared because of previous changes in master

So, it's finally in. If you have any additional patches fixing some forgotten stuff, please propose them soon, they will be merged faster than this crucial change.

Note: Merge reverted some rhn-client-tools language string changes done before Spacewalk 2.4 release. We will need to clarify procedure how to sync current translations with version on Zanata and how to avoid this kind of conflicts in future.

**Comment by moio** [comment]
@jdobes thank you very much for all the efforts here. I will be checking for new patches soon.

Have a nice day!

**Pull request closed without merging**
