### PR TITLE
sense support for debian packages

### PR DESCRIPTION
**Pull request by tlestach**
This is an attempt to fix Bug 1226329. However I do not have access to any debian machine. It would be great, if someone could check and test proposed changes.

### CODE REVIEW

**Comment by rpasche** [comment]
Hello @tlestach,

without yet trying...it looks good to me. Just another hint. According to https://www.debian.org/doc/debian-policy/ch-relationships.html there are 2 more senses. '<<' and '>>'.

**Comment by rpasche** [comment]
No. My fault. '<' should be changed to '<<' and '>' changed to '>>'.

**Comment by tlestach** [comment]
Good point, @rpasche! I updated the PR.

**Comment by rpasche** [comment]
Hi,

I'm sorry...but I need some help. I'm not familiar in building spacewalk from scratch. I can change the python code but how or "what" do I have to do to get the "tasktomatic" fixed and rebuilt?

Thanks for any help :-)

**Comment by tkasparek** [comment]
@rpasche If you want I can build spacewalk-java packages containing updated taskomatic code. Just let me know which spacewalk-java version are you using so I can build them.
For faster communication you can find me at #spacewalk and #spacewalk-devel IRC channels on irc.freenode.net.

**Comment by rpasche** [comment]
We are getting closer.

But I just found another problem with the "version" strings. In Debian, you can create dependencies in that you require package A or package B seperated by a "|". Look at the following lines

From original Packages.gz from Debian

```
Package: clamav-milter
...
Depends: adduser, clamav-base (>= 0.99+dfsg-0+deb8u2), clamav-freshclam (>= 0.99+dfsg) | clamav-data, dpkg (>= 1.16.1), logrotate, lsb-base (>= 3.2-13), procps (>= 1:3.3.2), ucf, debconf (>= 0.5) | debconf-2.0, libc6 (>= 2.15), libmilter1.0.1, libssl1.0.0 (>= 1.0.0)
```
You can either use ```clamav-freshclam``` or ```clamav-data``` and ```debconf``` or ```debconf-2.0```

Now the same package generated by spacewalk (with included patch)

```
Package: clamav-milter
...
Depends: adduser, clamav-base (>= 0.99+dfsg-0+deb8u2), clamav-freshclam(>=0.99+dfsg)|clamav-data, dpkg (>= 1.16.1), logrotate, lsb-base (>= 3.2-13), procps (>= 1:3.3.2), ucf, debconf(>=0.5)|debconf-2.0, libc6 (>= 2.15), libmilter1.0.1, libssl1.0.0 (>= 1.0.0)
```

When it comes to some "choice", the patch does not work anymore.

**Comment by hlawatschek** [comment]
Hi @tlestach, in my opinion the following change may be enough #437 to solve the issue.

**Comment by tlestach** [comment]
@hlawatschek, it's looks good ... this is what I actually planned to do :-)

**Comment by ggainey** [comment]
Accepted as d08f9bb9 - thanks for the fix!

**Comment by linedash** [comment]
Appears that this fix may not work.

Upgraded to nightly (2.6); rebuild my Packages files with:

 spacecmd "softwarechannel_regenerateyumcache debian8-x86_64-main"
 spacecmd "softwarechannel_regenerateyumcache debian8-x86_64-main-contrib"

Confirmed they had updated by checking time/date of packages{,.gz} and then ran apt-get clean all ; apt-get update:

E: Error occurred while processing games-adventure (NewVersion2)
E: Problem with MergeList /var/lib/apt/lists/spacewalk.redacted.com_dists_channels:_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.

Ran sed statement provided in bugzilla link:  https://bugzilla.redhat.com/show_bug.cgi?id=1226329

sed -e 's#(\([<>=]*\)\([^)]*\))#(\1 \2)#g' Packages | gzip -c > Packages.gz

Package games-adventure, games-arcade, etc now correctly parse.

old : Depends: games-tasks (=1)
new : Depends: games-tasks (= 1)

Note the space between = and 1.  This is required.

**Pull request closed without merging**
