### PR TITLE
clone config files without loosing trailing new lines

### PR DESCRIPTION
**Pull request by mcalmer**
Do not loose trailing new lines

### CODE REVIEW

**Comment by xkollar** [comment]
Hi. Could you please provide reproducer for undesired behaviour?

**Comment by mcalmer** [comment]
* create a config channel (e.g. origchannel)
* create a file in the config channel with (multiple) new lines at the end of the file

Example:

-------------------- begin file ------------------------
X=1


--------------------- end file -------------------------
* call spacecmd configchannel_clone origchannel -c clonechannel
* check the cloned file in clonechannel

all new lines got removed. It only contains "X=1" without the new lines at the end.

**Comment by xkollar** [comment]
I see. Thanks for the reproducer.

Playing with it, I have found out that there are more issues:
Not only trailing newline(s), but it seems to me like any trailing white-space is removed.
Also, any leading white-space is removed as well.

Would you try to fix those too please?

**Comment by sdherr** [comment]
Instead of accepting this commit I'm just changing spacecmd to always base64 encode config file contents, because why not, and it fixes all whitespace stripping problems. cd86ea1b8671596f025f378c5c06d6918ce6e7fc

**Pull request closed without merging**
