### PR TITLE
request repodata regeneration even if an erratum without new packages…

### PR DESCRIPTION
**Pull request by tlestach**
I've found this commit on an older computer. Honestly I'm not sure, whether the code still works or if it's complete. Creating PR to review the patch by the team.

### CODE REVIEW

**Comment by tkasparek** [comment]
Hello Tomas,

I've reviewed your patch and it does what's said in commit message. But I have no idea why we want to do this. By any chance is it possible that there was some BZ attached to that commit?

Thank you

**Comment by tlestach** [comment]
Not sure about any associated BZ. But if you sync an erratum without associated packages, you still want the erratum to appear in the repodata, right?

**Comment by ggainey** [comment]
text-only errata, would be my guess...

**Comment by ggainey** [comment]
Accepted as 0503cdea - thanks for the contribution!

**Pull request closed without merging**
