### PR TITLE
Add proper debian version handling to spacewalk

### PR DESCRIPTION
**Pull request by wraiden**
This fixes a few failures to match debian package versions in spacewalk channels with ones reported as installed from clients.

It changes the parsing to handle the debian package version components according to definitions from here: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version
It uses logic that is already inside of client/rhel/rhn-client-tools/src/up2date_client/debUtils.py in all relevant places.

It also fixes a failure to fetch packages with name containing hyphens.
It uses parts of #444 from @hlawatschek for this.

User-Notes:
After the update the channels must be cleaned and synced again to import the right versions.
The client needs to be fixed also to report an X instead of a 0 as release if it is empty.
(Which is wrong as some debian packages like **pyca** and **python-manila-ui** use a release value of 0)

### CODE REVIEW

**Comment by wraiden** [comment]
Can someone take a look why the local unsupported error gets thrown when this is checked?
This doesn't look like it is related to the changes made in any way (or is it?!):

ERROR: test_rfc822time_japan_locale (__main__.Tests)
rfc822time: Test result in ja_JP locale.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rhnLib.py", line 60, in test_rfc822time_japan_locale
    locale.setlocale(locale.LC_TIME, 'ja_JP')
  File "/usr/lib64/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
----------------------------------------------------------------------

**Comment by fritz001** [comment]
Hello,
Looks like latest update 2.6.49.1  for rhel/centoes6 breaks the effect of pull 500.
After applying all changes of pull 500, delete main channel [ debian 8 - jessie -> repo sync from custom debian repo ] , Packages.gz and Packages are generated incompletely  (  a lot of packages missing from Packages.gz in /var/cache/rhn/repodata/jessie-main )
- to reporduce: 
1.spacewalk 2.6 on centos 6 x64;
2. main channel -> jessie-main [ debian 8 -> sync from DVD1-4]
3 test install-> debian 8 installed minimal -> after register to spacewalk => apt-get install cinnamon-desktop-environment vlc <== got error not such package  cinnamon-desktop-environment , but package is present in the channel
 ++ if I keep changes from pull 444, ALL packages are OK, but I'm getting SIZE mismatch during apt-get upgrade

**Comment by wraiden** [comment]
Hello,

i run spacewalk-2.6 lately for patch-, errata- and configuration-management on ubuntu trusty and xenial and never got such errors.
I incorporated pull 444 mostly unchanged with adapted version parsing.
But we don't use the package repository portion of spacewalk-2.6 because of:
- missing package metadata information (like Multi-Arch) in the repository files created
  (spacewalk does not store everything during sync so it's unable to recreate it)
- missing gpg signing when creating the repository files
  (newer apt versions require this and setting 'APT::Get::AllowUnauthenticated "true";' is not an option if you take security serious)
- it also throws away the chain of trust by not importing and serving the upstream package signatures

Because all of the above we use apt-cacher-ng to proxy upstream repositories with all signatures intact to the clients.

1. Can you check if you got any backtraces from spacewalk during package-syncing, repository-creation or repository-fetching? (Check the logs in /var/log/rhn and /var/log/tomcat* and also the mails)
2. Can you provide a step by step guide to reproduce your spacewalk setup, the failure your getting and tell me which client-packages you use to fetch the package data from spacewalk?

I'll look into it after that...

**Comment by fritz001** [comment]
Hi Marc, 

External DB postgres 9.4 is used 

I will tray to be as precise as possible: 

1. I have created a custom repository of debian 8 jessie [ dvd 1-4] +
packages to allow install on apt-spacewalk [ 10966 packages ] 

2. spacewalk version 2.6.49.1 [ upgraded from 2.6.48.1 ] using official
spacewalk repo 

3. applying the pull 500 

4. create a base channel [ jessie-main ] 

5. sync the channel with the repo => 10966 packages  synced  w/o problem


Now, just by curiosity I was checking
/var/cache/rhn/repodata/jessie-main/* 

And both files Packages + Packages.gz were quite small  : Packages,
almost 2Mb and Packages.gz ~400K 

=============== 

Client test 

============== 

Install debian 8 mimimal, register it w/o 

apt-get update; apt-get install cinnamon-desktop-environment 

And here apt-get complains  that package does not exist "
cinnamon-desktop-environment" 

Now when I checked the packages of jessie-main channel ALL, cinnamon-*
packages were present alfo files on /var/satelllite/rhn/1*.... 

Also ALL cinnamon-* packages were not present to 
/var/cache/rhn/repodata/Packages* 

------------------------------------------------------- 

2nd spacewalk server 2.6.48.1 [ no upgrade yet ] 

------------------------------------------------------- 

same config, but only pull 444 applied => everything is working as
designed 

Now, if I apply patch 444 on spacewalk 2.6.49.1, ALL packages are
present in /var/cache/rhn/repodata/jessie-main/Packages.gz 

But this time, during apt-get upgrade, or apt-get install, to certain
packages I'm getting SIZE MISMATCH 

Latter in the evening can provide some logs 

Hope what I gave you so far can help you having a better idea  what
could be wrong. 

On 2017-03-06 11:13, Marc - A. Dahlhaus wrote:

> Hello, 
> 
> i run spacewalk-2.6 lately for patch-, errata- and configuration-management on ubuntu trusty and xenial and never got such errors.
> I incorporated pull 444 mostly unchanged with adapted version parsing.
> But we don't use the package repository portion of spacewalk-2.6 because of: 
> 
> * missing package metadata information (like Multi-Arch) in the repository files created
> (spacewalk does not store everything during sync so it's unable to recreate it) 
> * missing gpg signing when creating the repository files
> (newer apt versions require this and setting 'APT::Get::AllowUnauthenticated "true";' is not an option if you take security serious)     * it also throws away the chain of trust by not importing and serving the upstream package signatures
> 
> Because all of the above we use apt-cacher-ng to proxy upstream repositories with all signatures intact to the clients. 
> 
> * Can you check if you got any backtraces from spacewalk during package-syncing, repository-creation or repository-fetching? (Check the logs in /var/log/rhn and /var/log/tomcat* and also the mails)
> * Can you provide a step by step guide to reproduce your spacewalk setup, the failure your getting and tell me which client-packages you use to fetch the package data from spacewalk?
> 
> I'll look into it after that... 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/spacewalkproject/spacewalk/pull/500#issuecomment-284355095
[2]

**Comment by fritz001** [comment]
Some logs:
spacewalk 2.6.49.1 => pull 500  wiped out completely the channel recreate +sync 
=====================================================
INFO   | jvm 1    | 2017/03/07 22:55:58 | 2017-03-07 22:55:58,736 [Thread-43] WARN  com.redhat.rhn.taskomatic.core.SchedulerKernel - Number of interrupted runs: 1
INFO   | jvm 1    | 2017/03/07 23:00:01 | 2017-03-07 23:00:01,112 [DefaultQuartzScheduler_Worker-4] INFO  com.redhat.rhn.taskomatic.task.CompareConfigFilesTask - running config compare
INFO   | jvm 1    | 2017/03/07 23:00:01 | 2017-03-07 23:00:01,372 [DefaultQuartzScheduler_Worker-5] INFO  com.redhat.rhn.taskomatic.task.ClearLogHistory - Clearing log history older than: 2017-02-28 00:00:00 CET
INFO   | jvm 1    | 2017/03/07 23:01:00 | 2017-03-07 23:01:00,100 [DefaultQuartzScheduler_Worker-7] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
INFO   | jvm 1    | 2017/03/07 23:02:00 | 2017-03-07 23:02:00,321 [DefaultQuartzScheduler_Worker-1] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
INFO   | jvm 1    | 2017/03/07 23:12:00 | 2017-03-07 23:12:00,065 [DefaultQuartzScheduler_Worker-3] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata - In the queue: 1
INFO   | jvm 1    | 2017/03/07 23:12:00 | 2017-03-07 23:12:00,288 [Thread-155] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Removing jessie-main
INFO   | jvm 1    | 2017/03/07 23:13:00 | 2017-03-07 23:13:00,306 [DefaultQuartzScheduler_Worker-8] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata - In the queue: 1
INFO   | jvm 1    | 2017/03/07 23:13:00 | 2017-03-07 23:13:00,576 [Thread-161] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - File Modified Date:1970-01-01 01:00:00 CET
INFO   | jvm 1    | 2017/03/07 23:13:00 | 2017-03-07 23:13:00,576 [Thread-161] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Channel Modified Date:2017-03-07 23:11:44 CET
INFO   | jvm 1    | 2017/03/07 23:13:00 | 2017-03-07 23:13:00,679 [Thread-161] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Generating new DEB repository for channel jessie-main
INFO   | jvm 1    | 2017/03/07 23:13:42 | 2017-03-07 23:13:42,542 [DefaultQuartzScheduler_Worker-4] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask - Syncing repos for channel: jessie-main
INFO   | jvm 1    | 2017/03/07 23:22:11 | 2017-03-07 23:22:11,832 [Thread-166] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Spacewalk 7176 2017/03/07 23:13:42 +02:00: WARNING: log path not found; attempting to create /var/log/rhn/reposync
INFO   | jvm 1    | 2017/03/07 23:22:11 | Spacewalk 7176 2017/03/07 23:13:42 +02:00: (None, None)
INFO   | jvm 1    | 2017/03/07 23:22:11 |
INFO   | jvm 1    | 2017/03/07 23:22:11 | 2017-03-07 23:22:11,834 [Thread-165] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask - 23:13:42 ======================================
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:13:42 | Channel: jessie-main
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:13:42 | Channel: jessie-main
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:13:42 ======================================
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:13:42 Sync of channel started.
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:13:43 Repo URL: http://localhost/mrepo
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:13:43 Packages in repo:             10966
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:19:37 Packages already synced:          0
INFO   | jvm 1    | 2017/03/07 23:22:11 | 23:19:37 Packages to sync:             10966
....
....
INFO   | jvm 1    | 2017/03/07 23:22:12 | 23:22:11 Sync of channel completed in 0:18:28.
INFO   | jvm 1    | 2017/03/07 23:22:12 | 23:22:11 Total time: 0:18:28
INFO   | jvm 1    | 2017/03/07 23:22:12 |
INFO   | jvm 1    | 2017/03/07 23:23:00 | 2017-03-07 23:23:00,252 [DefaultQuartzScheduler_Worker-7] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
INFO   | jvm 1    | 2017/03/07 23:23:00 | 2017-03-07 23:23:00,273 [DefaultQuartzScheduler_Worker-8] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata - In the queue: 1
INFO   | jvm 1    | 2017/03/07 23:23:00 | 2017-03-07 23:23:00,305 [Thread-224] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - File Modified Date:2017-03-07 23:13:00 CET
INFO   | jvm 1    | 2017/03/07 23:23:00 | 2017-03-07 23:23:00,305 [Thread-224] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Channel Modified Date:2017-03-07 23:12:52 CET
INFO   | jvm 1    | 2017/03/07 23:23:00 | 2017-03-07 23:23:00,956 [Thread-224] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Generating new DEB repository for channel jessie-main
INFO   | jvm 1    | 2017/03/07 23:25:00 | 2017-03-07 23:25:00,422 [DefaultQuartzScheduler_Worker-1] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1

catalina.out = no errors

**Comment by fritz001** [comment]
apache logs 
============
[Tue Mar 07 23:26:12 2017] [error] \tSERVER_SOFTWARE: Apache
[Tue Mar 07 23:26:12 2017] [error] \tX-RHN-Auth: +dFYPzg1xc8o0jqdQxR70+ve2YNlawSRvByg5tvu51I=
[Tue Mar 07 23:26:12 2017] [error] \tX-RHN-Auth-Expire-Offset: 3600.0
[Tue Mar 07 23:26:12 2017] [error] \tX-RHN-Auth-Server-Time: 1488924090.79
[Tue Mar 07 23:26:12 2017] [error] \tX-RHN-Auth-User-Id:
[Tue Mar 07 23:26:12 2017] [error] \tX-RHN-Server-Id: 1000010074
[Tue Mar 07 23:26:12 2017] [error] \tX-RHN-Transport-Capability: follow-redirects=3
[Tue Mar 07 23:26:12 2017] [error] \tmod_ssl.is_https: <built-in method ssl_is_https of mod_wsgi.Adapter object at 0x7fa9404c5030>
[Tue Mar 07 23:26:12 2017] [error] \tmod_ssl.var_lookup: <built-in method ssl_var_lookup of mod_wsgi.Adapter object at 0x7fa9404c5030>
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.application_group: 192.168.50.5|/xmlrpc
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.callable_object: application
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.handler_script:
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.input_chunked: 0
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.listener_host:
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.listener_port: 80
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.process_group:
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.request_handler: wsgi-script
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.script_reloading: 1
[Tue Mar 07 23:26:12 2017] [error] \tmod_wsgi.version: (3, 2)
[Tue Mar 07 23:26:12 2017] [error] \twsgi.errors: <mod_wsgi.Log object at 0x7fa940473f70>
[Tue Mar 07 23:26:12 2017] [error] \twsgi.file_wrapper: <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7fa9404c5030>
[Tue Mar 07 23:26:12 2017] [error] \twsgi.input: <mod_wsgi.Input object at 0x7fa940473fb0>
[Tue Mar 07 23:26:12 2017] [error] \twsgi.multiprocess: True
[Tue Mar 07 23:26:12 2017] [error] \twsgi.multithread: False
[Tue Mar 07 23:26:12 2017] [error] \twsgi.run_once: False
[Tue Mar 07 23:26:12 2017] [error] \twsgi.url_scheme: http
[Tue Mar 07 23:26:12 2017] [error] \twsgi.version: (1, 1)
[Tue Mar 07 23:26:12 2017] [error] Extra information about this error:
[Tue Mar 07 23:26:12 2017] [error] Response sent back to the caller:
[Tue Mar 07 23:26:12 2017] [error] While running 'repodata': caught
[Tue Mar 07 23:26:12 2017] [error] <type 'exceptions.TypeError'> : repodata() takes exactly 2 arguments (3 given)
[Tue Mar 07 23:26:12 2017] [error]
[Tue Mar 07 23:26:12 2017] [error]
[Tue Mar 07 23:26:12 2017] [error]
[Tue Mar 07 23:26:12 2017] [error] Exception Handler Information
[Tue Mar 07 23:26:12 2017] [error] Traceback (most recent call last):
[Tue Mar 07 23:26:12 2017] [error]   File "/usr/lib/python2.6/site-packages/spacewalk/server/apacheRequest.py", line 135, in call_function
[Tue Mar 07 23:26:12 2017] [error]     response = func(*params)
[Tue Mar 07 23:26:12 2017] [error] TypeError: repodata() takes exactly 2 arguments (3 given)

**Comment by philicious** [comment]
@wraiden for GPG signing debian repositories in Spacewalk, you might want to have a look at my blogpost from late 2015 http://www.devops-blog.net/spacewalk/gpg-signing-apt-repository-in-spacewalk 
Maybe this can also help doing a proper PR for getting this natively into SW.
PS: I've written some more articles all around getting SW + Ubuntu/Debian to work up until 2.3
I'm about to check/evaluate how the situation changed/improved since then

**Comment by wraiden** [comment]
@philicious I know your blog, it was my starting point to setup a patch management service for ubuntu with spacewalk.
thanks for writing that.

what has changed since 2.3, is that spacewalk 2.6 now has a build in repository sync for deb repositories.
but it lacks support for some fields (eg. Multi-Arch).

the changed version handling in this pull request gets spacewalk to the point where it works mostly for patch management:

- it links the packages installed to the ones imported into spacewalk mostly correct
- it can install packages
- it can push configuration changes
- it can run commands
- push of events works with osad installed on the clients

but there are some rough edges that still needs fixing:

- kernel packages are not handled correctly (the packages are imported correctly but spacewalk does not compute the systems needing the kernel packages, i have a back trace but I'm still searching for the error itself / this also blocks the computation for errata handling for those packages)
- versions comparison is not handles right for debian packages (1.2.3-15 is newer as 1.2.3.4 as the difference between a dot and a hyphen is not handled correctly)

I have client packages for ubuntu trusty and xenial based on the rhel7-srpms for spacewalk 2.6 that i will share in a few days after changing the license information to state things correctly (I'll take a look if this builds on debian 8 also when reproducing the errors that @fritz001 gets).

**Comment by philicious** [comment]
@wraiden glad to hear it was helpful and fantastic news getting all this natively into SW now! Actually the 2.6 Changelog mentioning deb repo support got me excited and eventually lead me here.

Thanks for giving me the status quo. I guess I can skip some testing then. Will have a look into errata importing and see if my scripts still work/need fixes.

Ping me when you have the client packages ready. There are several required for various client functionality and some were outdated in the official repos while others only existed on launchpad and others needed patches. So I'm curious what we still might need to address.

kernel updates were working ok for me with SW 2.2 and hundreds of ubuntu 12/14 clients. but maybe its only causing problems for certain version strings and I was just lucky ?

Having Spacewalk GPG (re-)sign the deb repos with ones own key should be doable w/o breaking the chain of trust. I will look into that again and see if I can do a PR. Had that working fine with SW 2.2 with the patches shown in my blog.

**Comment by philicious** [comment]
so I did some testing and wanted to share my findings. Its a little offtopic but somehow related

Situation with the client packages:

Required packages for basic functionality (no OSAD, no config management). Versions are the availabe ones from xenial repo and >= the ones I had in use for longer time aswell as those following my articles or using my Chef cookbooks, so can be considered stable I'd say.
* apt-transport-spacewalk 1.0.6-4.1 (latest, but still misses errata apply action, my old ticket 
https://bugzilla.redhat.com/show_bug.cgi?id=1156338 , easy to fix tho. **needs to get updated**
* python-ethtool 0.11-3 (latest is 0.12-1 but is bad and causes segfault with rhnreg_ks on xenial , use 0.11-3, see my gist for backtrace and offending source https://gist.github.com/philicious/9851dc99087fc9289f42beab94f6af6b )
* python-rhn 2.5.55-2 (latest is 2.5.72-1, seems to work on xenial also)
* rhn-client-tools 1.8.26-4 (latest is 2.3.5, seems to work on xenial also) 
* rhnsd 5.0.4-3 (latest) 

Required packages for extended functionality (OSAD, config management, Remote command execution). These are not available in official repos but from launchpad here https://launchpad.net/~mj-casalogic/+archive/ubuntu/spacewalk-ubuntu/+packages (thx Martin Juhl) 
Would be nice if we could get them into official repos aswell.
* rhncfg_5.10.14-1 (misses to mkdir /var/spool/rhn/ )
* pyjabber_0.5.0-1.4
* osad_5.11.27-1
No other problems with them known to me 

I havent tested OSAD/Remote command execution again. Which requires additional packages only available from launchpad (rhncfg, pyjabber, osad). Will update this list later

**Comment by rpasche** [comment]
I would further suggest, to split the version in max. 2 parts at ":" sign. According to the source code of 'dpkg', the debian version string may also contain a colon ':', so something like 'apt_1:2:3.4-5-6.7' is also possible. 2:3.4-5 the version and 6-7 the revision.

It's a step further in the right direction for debian.

Look at the source code of 'dpkg' in lib/dpkg/test/t-version.c

**Comment by eherget** [comment]
I'm about to merge this pull request, but am looking for some help with the commit and build of the rhn-client-tools package that is part of the packages that debian ships.

**Comment by wraiden** [comment]
@eherget:
I will push an update to this PR to resolve the conflict in the next few days.
I will also push the debian directorys for the clients into a clients repo later this week...
@rpasche:
I'll have a look and try to catch that case also in the updated PR.

**Comment by eherget** [comment]
@wraiden  I've got the deb_src.py conflict resolved on my end.  I also fixed an issue where the Package.gz failed to get recreated.  Only thing I need is the debUtils.py change (rhn-client-tools...up2date_client) to make its way into the debian supplied package.

**Comment by rpasche** [comment]
@eherget what is the problem with the rhn-client-tools?

**Comment by wraiden** [comment]
@eherget :
Debian is still shipping Version 2.3.5-1 of rhn-client-tools.
I'd say we try to replace the packages with up to date packages from the 2.6 version.
I'll add the packaging resources to ja github tomorrow, they should build just fine in debian.

An official apt repository would be nice...
For debian and Ubuntu versions which are still supported...

**Comment by eherget** [comment]
Thank you for your contribution.  This has been merged into spacewalk git repo:
spacewalk-backend-2.7.117-1
spacewalk-java-2.7.92-1

The rhn-client-tools piece still needs to be merged into the debian git repos and the package built and released.

**Comment by philicious** [comment]
just to make sure its not missed: https://bugzilla.redhat.com/show_bug.cgi?id=1156338 (apt-transport-spacewalk still misses errata apply action)

**Comment by wraiden** [comment]
@philicious 
I'm currently working locally on a branch to add the Debian build system files i used to create the 2.6 packages back in January to the RHEL clients source directories and I'll also take care to add your errata.py to the apt-transport-spacewalk dir :)
but the push and resulting PR might take until Saturday...

**Comment by PPanon** [comment]
I recently updated @philicious' secure apt-get patches from https://bugzilla.redhat.com/show_bug.cgi?id=1198723 to work with Spacewalk 2.6. For the Spacewalk backend, On the client side, I had rebuilt my own trusty packages with current rhn lib version, so it should work with your updates and Ubuntu 16.04 (which adds InRelease repo files). On the server side, I'm running current Spacewalk package for CentOS 7. 

I'm trying to upload my new patches to Bugzilla for the above but, but can't seem to log in or create a new account. However I'm attaching them here if you want to look at incorporating them.
[spacewalkSecAptPatches.zip](https://github.com/spacewalkproject/spacewalk/files/1112992/spacewalkSecAptPatches.zip)

**Comment by PPanon** [comment]
P.S. I'm currently running into some issues where apt-get upgrade is getting a 404 file not found error when trying to apply updates from the server (even though the package is visible in the channel details and the path for that package does indeed point to a valid file. I asked Phil about it and he indicate it might be related to some version parsing bugs and pointed me here, so I'm really looking forward to your update :-)

**Comment by wraiden** [comment]
@PPanon 
i think it will take us quite a while to add proper signing support to the repository writer in spacewalk which we need to as the sync will destroy the signing every time it recreates the repository data.
the 404 errors are surely related to version parsing bugs which should be history after updating to the latest 2.7 packages and recreation of all apt repos.
it will not work just to resync repos the lin above that states "After the update the channels must be cleaned and synced again to import the right versions." basically means that you have to delete the channels and start over from scratch.

**Comment by wraiden** [comment]
this is because the packages from beore are imported with wrong information as the package version parsing importet the versions before with wrong epoch information. thus fetching packages with epoch that where imported with the old parser will fail to download...

**Comment by PPanon** [comment]
Thanks for you work on the version fixes.

Yes, I’m currently scheduling repo syncs within SW once a month, and running cron jobs to apply Errata afterwards (for CentOS and Ubuntu packages). I’m therefore also running the repo meta rebuild as part of the errata job. Now, if you put in the back-end changes for rhn_repository.py, and the client method changes I won’t have to re-apply my change with every package update ☺ If the signed repo files don’t exist, then I would think you would just get the same error on the client that you get now (unable to verify authenticity), so behaviour should be unchanged. That said, I admit I haven’t verified that would be the case, and due to the version errors I’m running into, I can’t easily do so. However if it does work as I expect, then putting in the patches wouldn’t break anything, and if users want to run a cron job to produce signed repo files until that functionality can be rolled in the SW repo sync functions, then they would have that option.

Cheers,

Paul-Andre Panon
Senior systems administrator

[Description: Description: cid:94E6F4C4-5B44-4347-9ED1-9EB642C99B07]
Office: 604.629.5182 ext 2341 Mobile: 604.679.1617

[Description: Description: cid:4B219234-8A15-44EF-AA55-A5E1DB0E5F05]
This email, including any files attached hereto (the “email”), contains privileged and confidential information and is only for the intended addressee(s). If this email has been sent to you in error, such sending does not constitute waiver of privilege and we request that you kindly delete the email and notify the sender. Any unauthorized use or disclosure of this email is prohibited. Avigilon and certain other trade names used herein are the registered and/or unregistered trademarks of Avigilon Corporation and/or its affiliates in Canada and other jurisdictions worldwide.

**Pull request closed without merging**
