### PR TITLE
Unit test fixes

### PR DESCRIPTION
**Pull request by moio**
These commits fix ~40 failing test cases after recent changes in the codebase (mainly the removal of monitoring code and the porting of pages to Perl).

### CODE REVIEW

**Comment by ggainey** [comment]
@moio - looks like we're missing updates to TaskConstants and Task_queries.xml for TaskConstants.TASK_QUERY_REPOMD_CANDIDATES_DETAILS_QUERY?

**Comment by moio** [comment]
@ggainey: missing code added, it's always good to reduce code distance, thanks for the heads-up :-)

**Comment by ggainey** [comment]
Awesome, everything looks good - merged and tagged as spacewalk-java-2.3.149-1

**Comment by xkollar** [comment]
I see that there are unmerged commits... is that intentional?

**Pull request closed without merging**
