### PR TITLE
Use consistent naming for SSM pages

### PR DESCRIPTION
**Pull request by moio**
This does the following:
 - change the SSM "main" pages title into "System Set Manager Overview". This is consistent with main pages of other features, eg. "Autoinstallation" -> "Autoinstallation Overview"
 - renames, both in the navigation menu and in the title, the "Status" page to "System Set Manager Task Log". This better reflects the content and is consistent with detail pages of other features, eg "Autoinstallation > Profiles" -> "Autoinstallation Profiles"
 - changes the ordering of tabs in the Task Log page, so that the tab opened by default ("All") is the first. This is also consistent with many other tabbed pages in the Web UI

Overview page example:
overview

Task Log page example:
tasklog

### CODE REVIEW

**Comment by eherget** [comment]
I'd like to pull in this useful enhancement.  My only concern is changing the name of the System Set Manager page to "System Set Manager Overview" when there is an "Overview" tab on the page in addition to several others.  Also, please make the "Task Log" vs "Tasks Log" consistent.

**Comment by moio** [comment]
> please make the "Task Log" vs "Tasks Log" consistent

Addressed.

> My only concern is changing the name of the System Set Manager page to "System Set Manager Overview" when there is an "Overview" tab on the page in addition to several others

I still find it better than the previous strings - what would you propose instead?

**Comment by eherget** [comment]
> I still find it better than the previous strings - what would you propose instead?

I would just leave it as "System Set Manager" since each tab will have its own subsection title.  It will also match the nav bar text as most of the other nav items do.

**Comment by eherget** [comment]
Thank you for your contribution!  I have pulled this in.  I did revert the System Set Manager page to its original name.  Having Overview in the title is inconsistent with our page titles and and the Overview tab is only 1 of 10 tags on this page.
This change appears in:
spacewalk-java-2.7.64-1

**Comment by moio** [comment]
Thanks!

**Pull request closed without merging**
