### PR TITLE
1244512 - deprecating useless method

### PR DESCRIPTION
**Pull request by xkollar**
See [Bug #1244512](https://bugzilla.redhat.com/show_bug.cgi?id=1244512) for more details.

### CODE REVIEW

**Comment by tomas-kasparek** [comment]
Well, this one is still used in UserHandlerTest, but it's true that it's not used in real code...

**Comment by ggainey** [comment]
Accepted as commit 510ca6b7 - thanks for the patch! :)

**Comment by xkollar** [comment]
@ggainey thanks for buying me ticket to the following release party `;-)`.

**Comment by tkasparek** [comment]
@xkollar This pull request was created during work on Spacewalk 2.4 and you have attended Spacewalk 2.4 release party. For ticket to the Spacewalk 2.5 release party, please create valid pull request during 2.5 development cycle.

**Comment by xkollar** [comment]
I remember process of creating invitation list slightly differently `;-)`. But I get it... things change `:-(`.

**Pull request closed without merging**
