### PR TITLE
fix --ca-chain option for rhnpush (bsc#931503, bsc#895869)

### PR DESCRIPTION
**Pull request by mantel**
option --ca-chain was not passed down to routines from up2date

### CODE REVIEW

**Comment by mantel** [comment]
I have no idea why the travis check for this PR fails. It works fine here in our own build system. If somebody points me to the cause of the problem, I will happily try to fix it. Otherwise feel free to close this PR. Our actual problem is fixed by those changes, I just wanted to send the fix upstream, since the --ca-chain option of rhnpush is broken.

**Comment by jdobes** [comment]
Please ignore travis for this PR, it's a bug - you made changes in two packages, they are building separately and they are taking dependencies from nightly repo instead of other packages from PR. Sorry for confusion.

**Comment by thedevicesupport** [comment]
http://www.thedevicesupport.com/
http://www.thedevicesupport.com/support-for-echo/
http://www.thedevicesupport.com/support-for-xbox/
http://www.thedevicesupport.com/support-for-skype/
http://www.thedevicesupport.com/kindle-support/
http://www.thedevicesupport.com/support-for-tablet/
https://www.thedevicesupport.com/support-for-magicjack/
http://www.thedevicesupport.com/support-for-google-pixel/
http://www.thedevicesupport.com/support-for-google-home/
http://www.rokuhelp.com/
http://www.rokuhelp.com/roku-activation-link/

**Comment by MichaelMraka** [comment]
The issue seems to be fixed on current spacewalk nightly (2.7). 
Closing.
Thanks for your contribution.

**Pull request closed without merging**
