### PR TITLE
Spacecmd with python3

### PR DESCRIPTION
**Pull request by mcalmer**
port spacecmd and make it python3 compatible

### CODE REVIEW

**Comment by eherget** [comment]
This PR fails to build.  Have a look at the detail of the Travis CI build - specifically the build log.

**Comment by mcalmer** [comment]
@eherget - please check again. I doubt that this error is caused by one of my changes:
```
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)]
************* Module spacecmd.utils
E: 54, 0: Unable to import 'rpm' (import-error)
```

python3-rpm as well as rpm-python is buildrequired. For python2 nothing should be changed in the dependencies. Any idea what cause the error?

**Comment by eherget** [comment]
@mcalmer - Its failing on Fedora 26 and 27.  It requires spacewalk-pylint, which is pulling in a lot of python2 packages.  These ultimately seem to make rpm from the python3-rpm package not visible.  When I remove the requirement for spacewalk-pylint, the build succeeds.  I'm digging in on my side to see how this needs to be handled... maybe update spacewalk-pylint to use python3, etc.

**Comment by mcalmer** [comment]
Thanks

**Comment by eherget** [comment]
I have added several commits to complete the support for python3 and merged this manually.  This will appear in spacecmd-2.8.17-1

**Pull request closed without merging**
