### PR TITLE
1436634 - Fix KS Default Download Location appending URL verbatim.

### PR DESCRIPTION
**Pull request by lrochfor-oracle**
Fix a bug introduced as described in the BZ, whereby a Kickstart distro-tree path is appended verbatim to the SW/proxy host in the "url" field of the Kickstart file.

This fix also incorporates the functionality that was intended to be introduced by the BZ that introduced the bug. Specifically, if a path starting wiht a "/", that is not the distro-tree path, is entered it should be appended to the automatically derived SW/proxy host in the "url" field of the Kickstart file.

Paths starting with http or ftp are just inserted verbatim.

### CODE REVIEW

**Comment by lrochfor-oracle** [comment]
http://ftp.heanet.ie/pub/jpackage/5.0/generic/free/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

Would you please investigate?

**Comment by thedevicesupport** [comment]
https://www.thedevicesupport.com/support-for-magicjack/

**Comment by phillipskimberly** [comment]
https://www.thedevicesupport.com/support-for-magicjack/
https://www.thedevicesupport.com/kindle-support/
https://www.thedevicesupport.com/support-for-echo/

**Comment by eherget** [comment]
KickstartUrlHelper lines 260 and 274: Please update these to fix the use of StringBuilder.    The strings are being concatenated with the '+' operator, with the result passed as an arg to the append() method.  This defeats the purpose of using StringBuilder.  :)    If you prefer this happen on one line, you can use url.append(protocol).append(host).append()...

**Comment by lrochfor-oracle** [comment]
Travis build is failing with 404 for jpackage as per previous comment.

**Comment by eherget** [comment]
I've updated the BZ with request for info.  Please have a look there.

**Comment by lrochfor-oracle** [comment]
Requested info provided in BZ.

https://bugzilla.redhat.com/show_bug.cgi?id=1436634#c5

**Comment by jdobes** [comment]
I fixed travis build and now checkstyle complains about:

code/src/com/redhat/rhn/manager/kickstart/KickstartUrlHelper.java:260:1: File contains tab characters (this is the first instance). [FileTabCharacter]

could you look at it, please?

**Comment by eherget** [comment]
I fixed the checkstyle issues with tab chars and pulled this fix in.  Thank you for your contribution!
This is available in spacewalk-java-2.7.69-1

**Pull request closed without merging**
