### PR TITLE
Use different symbols for collapsible sidebar items

### PR DESCRIPTION
**Pull request by moio**
This makes it easier to distinguish menu items visually:
 - use a small circle for items that have no child items
 - use a rightward pointing arrow for items that are collapsed
 - use a downward pointing arrow for items that are uncollapsed

Before:
before

After:
after

### CODE REVIEW

**Comment by moio** [comment]
Note: this needs Java 8

**Comment by thedevicesupport** [comment]
https://www.thedevicesupport.com/support-for-echo/

**Comment by thedevicesupport** [comment]
http://www.thedevicesupport.com/
http://www.thedevicesupport.com/support-for-echo/
http://www.thedevicesupport.com/support-for-xbox/
http://www.thedevicesupport.com/support-for-skype/
http://www.thedevicesupport.com/kindle-support/
http://www.thedevicesupport.com/support-for-tablet/
https://www.thedevicesupport.com/support-for-magicjack/
http://www.thedevicesupport.com/support-for-google-pixel/
http://www.thedevicesupport.com/support-for-google-home/
http://www.rokuhelp.com/
http://www.rokuhelp.com/roku-activation-link/

**Comment by eherget** [comment]
Thank you for the contribution here, I think it is a nice enhancement.  There are two changes I'd like to see:
1) we need to support java versions < 1.8, so the java.util.streams should come out.
2) the small 'o' (I think it might be the degree symbol) is just a bit too small.  I'm not sure what to replace it with.  I played with replacing f105 with f0da, f107 with f0d7 and then use f105 in place of the small circle.

**Comment by eherget** [comment]
Thank you for your contribution!  I've pulled it in as-is, and then added a change to support java versions < 1.8 (by removing java.util.stream stuff).  This will appear in:
spacewalk-branding-2.7.4-1
spacewalk-java-2.7.63-1

**Comment by moio** [comment]
Thanks!

**Comment by eherget** [comment]
I just fixed an issue with child nav items not displaying as active.  This was introduced when I did fix to support java versions < 1.8.  This fix appears in:
spacewalk-java-2.7.9-1

**Pull request closed without merging**
