### PR TITLE
Cobbler Distro metadata fixing & refactoring, Improving kernel options handling

### PR DESCRIPTION
**Pull request by hustodemon**
### 1st part (hustodemon)
- Unification of kickstart metadata handling accross scenarios (previously some parts of metadata were missing in some scenarios)
- Code de-duplication by pulling common code to a helper class
- Refactored tests, added more tests
### 2nd part (lucidd)
- Making Cobbler distro's "kernel options" and "kernel options post" part of the `KickstartableTree` and make this persistent (previously they were only stored in cobbler and couldn't be recreated by spacewalk when the cobbler entry was deleted)
- Refactoring

### CODE REVIEW

**Comment by jdobes** [comment]
If I run:
# ant -f /usr/share/rhn/unittest.xml -Dtestcase=CobblerCommandTest

It results in:
Testcase: testProfileCreate took 8,84 sec
Testcase: testProfileEdit took 2,1 sec
Testcase: testProfileDelete took 1,81 sec
Testcase: testDistroSync took 1,58 sec
        FAILED
null
junit.framework.AssertionFailedError
        at com.redhat.rhn.manager.kickstart.cobbler.test.CobblerCommandTest.testDistroSync(CobblerCommandTest.java:125)

Testcase: testDistroDelete took 1,65 sec
Testcase: testLogin took 1,76 sec
Testcase: testSystemCreate took 2,12 sec

Is it OK?

**Comment by hustodemon** [comment]
That doesn't look good and I'll recheck. Thanks for this!

**Comment by hustodemon** [comment]
I don't know what's in your **/usr/share/rhn/unittest.xml**, but when I use the one in the **java/scripts/unittest.xml** the tests passes OK.

I also ran the tests using my IDE and then using `ant test` command too and it runs OK as well.

I suppose you are testing that on a running spacewalk instance (because you're using that **unittest.xml** ant file) -- did you upgrade the db? Also, could you provide more debugging information (`-v -d` flags)? I'm really curious on what's going on here.

Thanks!

**Comment by jdobes** [comment]
I will recheck it again with clean spacewalk installation and I'll let you know.

**Comment by jdobes** [comment]
Well, it seems it was completely my fault, it's passing now. Sorry.

**Comment by hustodemon** [comment]
No problem :smile:

**Comment by jdobes** [comment]
So I reviewed all changes, it seems reasonable. Only quick question:

What's the motivation for saving kernel options in DB? And I see it's done only for kickstart trees, kickstart profiles still save/load their kernel options directly to/from cobbler, why?

**Comment by thedevicesupport** [comment]
http://www.thedevicesupport.com/
http://www.thedevicesupport.com/support-for-echo/
http://www.thedevicesupport.com/support-for-xbox/
http://www.thedevicesupport.com/support-for-skype/
http://www.thedevicesupport.com/kindle-support/
http://www.thedevicesupport.com/support-for-tablet/
https://www.thedevicesupport.com/support-for-magicjack/
http://www.thedevicesupport.com/support-for-google-pixel/
http://www.thedevicesupport.com/support-for-google-home/
http://www.rokuhelp.com/
http://www.rokuhelp.com/roku-activation-link/

**Comment by jdobes** [comment]
Rebased to master. Thanks.

**Pull request closed without merging**
